import {
  answerCivilClaimsQuestion,
  buildCivilClaimMatrix,
  buildCivilWholeMatterView,
  formatCivilClaimsAnswer,
  type CivilClaimsReview,
  type CivilSourceProvenance,
} from "./claims-model";

const PROV = (documentId: string, span: string, pleadingId: string | null = null): CivilSourceProvenance => ({
  documentId,
  sourceSpan: span,
  sourcePage: 1,
  pleadingId,
  humanEntered: false,
  extractionOrigin: "deterministic_fixture",
});

/**
 * Complex civil fixture for Deepening Pass 3:
 * - 2 defendants (Acme + Beta)
 * - Plaintiff River Co.
 * - Claims: breach (current, amended allegation), statutory unfair-trade (added in amendment)
 * - Superseded: negligent misrepresentation removed by amendment
 * - Counterclaim: unpaid invoices
 * - Defenses: element-negating (no breach), affirmative (waiver), notice
 * - Shared notice letter with different roles
 * - Party-specific evidence
 */
export function runComplexCivilClaimsFixture(): {
  review: CivilClaimsReview;
  matrix: ReturnType<typeof buildCivilClaimMatrix>;
  whole: ReturnType<typeof buildCivilWholeMatterView>;
  askText: string;
} {
  const review: CivilClaimsReview = {
    matterId: "matter-civil-d3",
    organizationId: "org-synthetic-firm",
    jurisdiction: "US",
    forumCourtId: "us-d-pa-ed",
    parties: [
      { id: "party-river", displayName: "River Co.", entityType: "organization" },
      { id: "party-acme", displayName: "Acme LLC", entityType: "organization" },
      { id: "party-beta", displayName: "Beta Inc.", entityType: "organization" },
    ],
    pleadings: [
      {
        id: "plead-complaint",
        label: "Original Complaint",
        filedAt: "2026-01-10",
        supersededByPleadingId: "plead-amended",
        supersedesPleadingId: null,
        isCurrent: false,
        provenance: PROV("doc-complaint", "Original complaint caption and claims.", "plead-complaint"),
      },
      {
        id: "plead-amended",
        label: "Amended Complaint",
        filedAt: "2026-03-01",
        supersededByPleadingId: null,
        supersedesPleadingId: "plead-complaint",
        isCurrent: true,
        provenance: PROV("doc-amended", "Amended complaint supersedes prior pleading.", "plead-amended"),
      },
      {
        id: "plead-answer",
        label: "Answer and Counterclaim",
        filedAt: "2026-03-20",
        supersededByPleadingId: null,
        supersedesPleadingId: null,
        isCurrent: true,
        provenance: PROV("doc-answer", "Answer asserting defenses and counterclaim.", "plead-answer"),
      },
    ],
    facts: [
      {
        id: "fact-contract",
        text: "River and Acme signed a supply agreement dated 2025-06-01.",
        relatedPartyIds: ["party-river", "party-acme"],
        provenance: PROV("doc-contract", "Signature block dated 2025-06-01."),
      },
      {
        id: "fact-notice",
        text: "River sent a written cure notice dated 2025-11-02.",
        relatedPartyIds: ["party-river", "party-acme"],
        provenance: PROV("doc-notice", "Notice letter dated 2025-11-02."),
      },
      {
        id: "fact-beta-email",
        text: "Beta email discusses only Beta's delivery schedule.",
        relatedPartyIds: ["party-beta"],
        provenance: PROV("doc-beta-email", "Beta-only schedule email."),
      },
      {
        id: "fact-invoice",
        text: "Acme invoice #441 remains unpaid on the recorded ledger.",
        relatedPartyIds: ["party-acme", "party-river"],
        provenance: PROV("doc-invoice", "Invoice #441 ledger line."),
      },
    ],
    evidence: [
      {
        id: "ev-contract",
        label: "Supply agreement",
        documentId: "doc-contract",
        relatedPartyIds: ["party-river", "party-acme"],
        provenance: PROV("doc-contract", "Contract exhibit."),
      },
      {
        id: "ev-notice",
        label: "Cure notice letter",
        documentId: "doc-notice",
        relatedPartyIds: ["party-river", "party-acme"],
        provenance: PROV("doc-notice", "Notice exhibit."),
      },
      {
        id: "ev-log",
        label: "Recipient delivery log",
        documentId: "doc-log",
        relatedPartyIds: ["party-acme"],
        provenance: PROV("doc-log", "Log with no notice entry."),
      },
      {
        id: "ev-beta-email",
        label: "Beta schedule email",
        documentId: "doc-beta-email",
        relatedPartyIds: ["party-beta"],
        provenance: PROV("doc-beta-email", "Beta-only email."),
      },
      {
        id: "ev-invoice",
        label: "Invoice 441",
        documentId: "doc-invoice",
        relatedPartyIds: ["party-acme", "party-river"],
        provenance: PROV("doc-invoice", "Invoice exhibit."),
      },
      {
        id: "ev-shared-scene",
        label: "Joint warehouse photo",
        documentId: "doc-scene",
        relatedPartyIds: ["party-acme", "party-beta"],
        provenance: PROV("doc-scene", "Photo showing shared dock."),
      },
    ],
    claims: [
      {
        id: "claim-breach-v1",
        kind: "CLAIM",
        category: "CONTRACT",
        label: "Breach of contract (original allegation)",
        description: "Original complaint alleged late delivery without specifying cure notice date.",
        parties: [
          { partyId: "party-river", role: "PLAINTIFF" },
          { partyId: "party-acme", role: "DEFENDANT" },
        ],
        supportStatus: "PARTIALLY_SUPPORTED",
        proceduralStatus: "SUPERSEDED",
        pleadingId: "plead-complaint",
        supersededByClaimId: "claim-breach",
        supersedesClaimId: null,
        isCurrent: false,
        elements: [
          {
            id: "el-breach-v1-duty",
            claimId: "claim-breach-v1",
            label: "Duty",
            requirementText: "A contractual duty existed.",
            status: "SUPPORTED",
            supportingEvidence: [{ evidenceId: "ev-contract", role: "SUPPORTS", partyIds: ["party-acme"], note: null }],
            contraryEvidence: [],
            missingEvidence: [],
            factRelations: [{ factId: "fact-contract", role: "SUPPORTS", partyIds: ["party-acme"], note: null }],
            authorities: [],
            standards: [],
            uncertainty: [],
            provenance: PROV("doc-complaint", "Original duty allegation.", "plead-complaint"),
          },
        ],
        legalIssueIds: ["issue-breach"],
        authorities: [],
        standards: [],
        damagesOrRemedy: null,
        uncertainty: ["Superseded by amended breach claim."],
        provenance: PROV("doc-complaint", "Count I original.", "plead-complaint"),
        liabilityConclusion: null,
      },
      {
        id: "claim-breach",
        kind: "CLAIM",
        category: "CONTRACT",
        label: "Breach of contract",
        description: "Amended claim alleges Acme failed to cure after written notice dated 2025-11-02.",
        parties: [
          { partyId: "party-river", role: "PLAINTIFF" },
          { partyId: "party-acme", role: "DEFENDANT" },
        ],
        supportStatus: "PARTIALLY_SUPPORTED",
        proceduralStatus: "AMENDED",
        pleadingId: "plead-amended",
        supersededByClaimId: null,
        supersedesClaimId: "claim-breach-v1",
        isCurrent: true,
        elements: [
          {
            id: "el-breach-duty",
            claimId: "claim-breach",
            label: "Duty",
            requirementText: "A contractual duty existed between River and Acme.",
            status: "SUPPORTED",
            supportingEvidence: [{ evidenceId: "ev-contract", role: "SUPPORTS", partyIds: ["party-acme"], note: null }],
            contraryEvidence: [],
            missingEvidence: [],
            factRelations: [{ factId: "fact-contract", role: "SUPPORTS", partyIds: ["party-acme"], note: null }],
            authorities: [
              {
                authorityId: "auth-synth-contract",
                citation: "SYNTHETIC-3D-2020-001",
                title: "Synthetic contract elements example",
                relation: "BINDING",
                treatment: "UNVERIFIED",
                currentness: "unknown",
                proposition: "Synthetic source span: contract claims are reviewed element by element.",
                sourceSpan: "Synthetic source span: contract claims are reviewed element by element.",
                sourceSupported: true,
                target: "element",
                targetId: "el-breach-duty",
              },
            ],
            standards: [
              {
                id: "std-duty",
                label: "Contract duty",
                standardType: "ELEMENT",
                text: "Existence of an enforceable duty under the recorded agreement.",
                sourceSpan: "Synthetic standard span for duty.",
                target: "element",
                targetId: "el-breach-duty",
              },
            ],
            uncertainty: [],
            provenance: PROV("doc-amended", "Amended duty allegation.", "plead-amended"),
          },
          {
            id: "el-breach-breach",
            claimId: "claim-breach",
            label: "Breach",
            requirementText: "Acme failed to perform after the recorded cure notice.",
            status: "CONFLICTED",
            supportingEvidence: [
              { evidenceId: "ev-notice", role: "SUPPORTS", partyIds: ["party-acme"], note: "Supports notice-and-breach sequence." },
              { evidenceId: "ev-shared-scene", role: "RELATED_TO", partyIds: ["party-acme", "party-beta"], note: "Shared dock photo; not alone a breach." },
            ],
            contraryEvidence: [
              { evidenceId: "ev-log", role: "CONTRADICTS", partyIds: ["party-acme"], note: "Log undermines notice receipt." },
            ],
            missingEvidence: [{ id: "missing-delivery", description: "Delivery receipt for the cure notice is not in the record." }],
            factRelations: [{ factId: "fact-notice", role: "SUPPORTS", partyIds: ["party-acme"], note: null }],
            authorities: [],
            standards: [],
            uncertainty: ["Notice delivery is disputed."],
            provenance: PROV("doc-amended", "Amended breach allegation with notice date.", "plead-amended"),
          },
          {
            id: "el-breach-damages",
            claimId: "claim-breach",
            label: "Damages",
            requirementText: "River incurred recoverable damages from the alleged breach.",
            status: "NO_EVIDENCE_FOUND",
            supportingEvidence: [],
            contraryEvidence: [],
            missingEvidence: [{ id: "missing-damages", description: "No damages worksheet or invoice tying loss to Acme breach." }],
            factRelations: [],
            authorities: [],
            standards: [],
            uncertainty: ["Damages quantum is unknown."],
            provenance: PROV("doc-amended", "Damages requested without exhibit.", "plead-amended"),
          },
        ],
        legalIssueIds: ["issue-breach", "issue-damages"],
        authorities: [],
        standards: [],
        damagesOrRemedy: {
          category: "compensatory",
          remedySought: "money damages",
          notes: "Quantum not evidenced.",
        },
        uncertainty: ["Breach element remains conflicted pending notice proof."],
        provenance: PROV("doc-amended", "Count I amended.", "plead-amended"),
        liabilityConclusion: null,
      },
      {
        id: "claim-negligent-misrep",
        kind: "CLAIM",
        category: "TORT",
        label: "Negligent misrepresentation",
        description: "Original Count II; removed in the amended complaint.",
        parties: [
          { partyId: "party-river", role: "PLAINTIFF" },
          { partyId: "party-acme", role: "DEFENDANT" },
          { partyId: "party-beta", role: "DEFENDANT" },
        ],
        supportStatus: "UNKNOWN",
        proceduralStatus: "WITHDRAWN",
        pleadingId: "plead-complaint",
        supersededByClaimId: null,
        supersedesClaimId: null,
        isCurrent: false,
        elements: [
          {
            id: "el-misrep-statement",
            claimId: "claim-negligent-misrep",
            label: "False statement",
            requirementText: "A false statement of material fact was made.",
            status: "UNKNOWN",
            supportingEvidence: [],
            contraryEvidence: [],
            missingEvidence: [{ id: "missing-statement", description: "No statement exhibit remains attached after withdrawal." }],
            factRelations: [],
            authorities: [],
            standards: [],
            uncertainty: ["Claim withdrawn; do not treat as current."],
            provenance: PROV("doc-complaint", "Count II original.", "plead-complaint"),
          },
        ],
        legalIssueIds: ["issue-misrep"],
        authorities: [],
        standards: [],
        damagesOrRemedy: null,
        uncertainty: ["Superseded pleading only."],
        provenance: PROV("doc-complaint", "Count II original.", "plead-complaint"),
        liabilityConclusion: null,
      },
      {
        id: "claim-unfair-trade",
        kind: "CLAIM",
        category: "STATUTORY",
        label: "Statutory unfair-trade practices",
        description: "Added in amended complaint against Acme and Beta on shared warehouse conduct.",
        parties: [
          { partyId: "party-river", role: "PLAINTIFF" },
          { partyId: "party-acme", role: "DEFENDANT" },
          { partyId: "party-beta", role: "DEFENDANT" },
        ],
        supportStatus: "PARTIALLY_SUPPORTED",
        proceduralStatus: "PLED",
        pleadingId: "plead-amended",
        supersededByClaimId: null,
        supersedesClaimId: null,
        isCurrent: true,
        elements: [
          {
            id: "el-utp-conduct",
            claimId: "claim-unfair-trade",
            label: "Unfair conduct",
            requirementText: "Defendants engaged in unfair or deceptive conduct in trade.",
            status: "PARTIALLY_SUPPORTED",
            supportingEvidence: [
              { evidenceId: "ev-shared-scene", role: "SUPPORTS", partyIds: ["party-acme", "party-beta"], note: "Shared evidence may support both defendants where linked." },
            ],
            contraryEvidence: [],
            missingEvidence: [{ id: "missing-utp-statute-facts", description: "No consumer-facing representation exhibit is attached." }],
            factRelations: [],
            authorities: [
              {
                authorityId: "auth-synth-utp",
                citation: "SYNTHETIC-EDPA-UTP-001",
                title: "Synthetic unfair-trade example",
                relation: "PERSUASIVE",
                treatment: "UNVERIFIED",
                currentness: "unknown",
                proposition: "Synthetic source span: statutory unfair-trade claims need recorded consumer-facing conduct.",
                sourceSpan: "Synthetic source span: statutory unfair-trade claims need recorded consumer-facing conduct.",
                sourceSupported: true,
                target: "element",
                targetId: "el-utp-conduct",
              },
            ],
            standards: [],
            uncertainty: ["Beta-specific schedule email does not automatically prove Acme unfair conduct."],
            provenance: PROV("doc-amended", "Count II amended statutory claim.", "plead-amended"),
          },
          {
            id: "el-utp-beta-only",
            claimId: "claim-unfair-trade",
            label: "Beta schedule representation",
            requirementText: "Beta made a schedule representation at issue.",
            status: "SUPPORTED",
            supportingEvidence: [
              { evidenceId: "ev-beta-email", role: "SUPPORTS", partyIds: ["party-beta"], note: "Defendant-specific; must not auto-support Acme." },
            ],
            contraryEvidence: [],
            missingEvidence: [],
            factRelations: [{ factId: "fact-beta-email", role: "SUPPORTS", partyIds: ["party-beta"], note: null }],
            authorities: [],
            standards: [],
            uncertainty: [],
            provenance: PROV("doc-beta-email", "Beta-only schedule email.", "plead-amended"),
          },
        ],
        legalIssueIds: ["issue-utp"],
        authorities: [],
        standards: [],
        damagesOrRemedy: {
          category: "statutory",
          remedySought: "statutory damages and fees",
          notes: null,
        },
        uncertainty: [],
        provenance: PROV("doc-amended", "Count II amended.", "plead-amended"),
        liabilityConclusion: null,
      },
      {
        id: "claim-counter-invoice",
        kind: "COUNTERCLAIM",
        category: "CONTRACT",
        label: "Counterclaim for unpaid invoices",
        description: "Acme counterclaims against River for invoice #441.",
        parties: [
          { partyId: "party-acme", role: "COUNTERCLAIMANT" },
          { partyId: "party-river", role: "COUNTERCLAIM_DEFENDANT" },
        ],
        supportStatus: "SUPPORTED",
        proceduralStatus: "PLED",
        pleadingId: "plead-answer",
        supersededByClaimId: null,
        supersedesClaimId: null,
        isCurrent: true,
        elements: [
          {
            id: "el-counter-amount",
            claimId: "claim-counter-invoice",
            label: "Amount due",
            requirementText: "An unpaid amount is recorded on invoice #441.",
            status: "SUPPORTED",
            supportingEvidence: [{ evidenceId: "ev-invoice", role: "SUPPORTS", partyIds: ["party-river"], note: null }],
            contraryEvidence: [],
            missingEvidence: [],
            factRelations: [{ factId: "fact-invoice", role: "SUPPORTS", partyIds: ["party-river"], note: null }],
            authorities: [],
            standards: [],
            uncertainty: [],
            provenance: PROV("doc-answer", "Counterclaim Count I.", "plead-answer"),
          },
        ],
        legalIssueIds: ["issue-counter"],
        authorities: [],
        standards: [],
        damagesOrRemedy: {
          category: "compensatory",
          remedySought: "unpaid invoice amount",
          notes: null,
        },
        uncertainty: [],
        provenance: PROV("doc-answer", "Counterclaim.", "plead-answer"),
        liabilityConclusion: null,
      },
    ],
    defenses: [
      {
        id: "def-no-breach",
        kind: "ELEMENT_NEGATING",
        label: "No breach / performance",
        description: "Acme asserts performance and denies breach of the supply agreement.",
        againstClaimIds: ["claim-breach"],
        assertingPartyIds: ["party-acme"],
        targetPartyIds: ["party-river"],
        supportStatus: "PARTIALLY_SUPPORTED",
        proceduralStatus: "PLED",
        pleadingId: "plead-answer",
        isCurrent: true,
        elements: [
          {
            id: "el-def-performance",
            claimId: "def-no-breach",
            label: "Performance",
            requirementText: "Acme performed the recorded contractual obligations.",
            status: "PARTIALLY_SUPPORTED",
            supportingEvidence: [{ evidenceId: "ev-shared-scene", role: "RELATED_TO", partyIds: ["party-acme"], note: null }],
            contraryEvidence: [{ evidenceId: "ev-notice", role: "UNDERMINES", partyIds: ["party-acme"], note: "Notice letter raises a performance dispute." }],
            missingEvidence: [],
            factRelations: [],
            authorities: [],
            standards: [],
            uncertainty: ["Performance proof is incomplete."],
            provenance: PROV("doc-answer", "Denial of breach.", "plead-answer"),
          },
        ],
        evidence: [
          { evidenceId: "ev-shared-scene", role: "RELATED_TO", partyIds: ["party-acme"], note: null },
          { evidenceId: "ev-notice", role: "UNDERMINES", partyIds: ["party-acme"], note: null },
        ],
        factRelations: [],
        authorities: [],
        standards: [],
        legalIssueIds: ["issue-breach"],
        uncertainty: [],
        provenance: PROV("doc-answer", "Element-negating defense.", "plead-answer"),
        validityConclusion: null,
      },
      {
        id: "def-waiver",
        kind: "AFFIRMATIVE",
        label: "Waiver",
        description: "Acme asserts River waived strict compliance by continued ordering.",
        againstClaimIds: ["claim-breach"],
        assertingPartyIds: ["party-acme"],
        targetPartyIds: ["party-river"],
        supportStatus: "UNKNOWN",
        proceduralStatus: "PLED",
        pleadingId: "plead-answer",
        isCurrent: true,
        elements: [
          {
            id: "el-def-waiver",
            claimId: "def-waiver",
            label: "Knowing waiver",
            requirementText: "River knowingly waived the claimed right.",
            status: "NO_EVIDENCE_FOUND",
            supportingEvidence: [],
            contraryEvidence: [
              { evidenceId: "ev-notice", role: "UNDERMINES", partyIds: ["party-acme"], note: "Cure notice may undermine waiver." },
            ],
            missingEvidence: [{ id: "missing-waiver", description: "No continued-ordering waiver exhibit is attached." }],
            factRelations: [{ factId: "fact-notice", role: "UNDERMINES", partyIds: ["party-acme"], note: "Same notice fact, different role than on breach." }],
            authorities: [],
            standards: [],
            uncertainty: ["Waiver remains unproven."],
            provenance: PROV("doc-answer", "Affirmative defense — waiver.", "plead-answer"),
          },
        ],
        evidence: [{ evidenceId: "ev-notice", role: "UNDERMINES", partyIds: ["party-acme"], note: null }],
        factRelations: [{ factId: "fact-notice", role: "UNDERMINES", partyIds: ["party-acme"], note: null }],
        authorities: [
          {
            authorityId: "auth-synth-waiver",
            citation: "SYNTHETIC-2D-2019-014",
            title: "Synthetic waiver example",
            relation: "PERSUASIVE",
            treatment: "UNVERIFIED",
            currentness: "unknown",
            proposition: "Synthetic source span: waiver requires knowing relinquishment supported by the record.",
            sourceSpan: "Synthetic source span: waiver requires knowing relinquishment supported by the record.",
            sourceSupported: true,
            target: "defense",
            targetId: "def-waiver",
          },
        ],
        standards: [],
        legalIssueIds: ["issue-waiver"],
        uncertainty: [],
        provenance: PROV("doc-answer", "Affirmative defense.", "plead-answer"),
        validityConclusion: null,
      },
      {
        id: "def-notice",
        kind: "NOTICE",
        label: "Statutory notice defense",
        description: "Acme asserts required statutory notice was not delivered.",
        againstClaimIds: ["claim-unfair-trade", "claim-breach"],
        assertingPartyIds: ["party-acme"],
        targetPartyIds: ["party-river"],
        supportStatus: "CONFLICTED",
        proceduralStatus: "PLED",
        pleadingId: "plead-answer",
        isCurrent: true,
        elements: [
          {
            id: "el-def-notice",
            claimId: "def-notice",
            label: "Notice delivery",
            requirementText: "Required notice was not delivered as alleged.",
            status: "CONFLICTED",
            supportingEvidence: [{ evidenceId: "ev-log", role: "SUPPORTS", partyIds: ["party-acme"], note: "Empty log supports non-delivery theory." }],
            contraryEvidence: [{ evidenceId: "ev-notice", role: "CONTRADICTS", partyIds: ["party-acme"], note: "Notice letter contradicts non-sending; delivery still open." }],
            missingEvidence: [{ id: "missing-delivery", description: "Delivery receipt for the cure notice is not in the record." }],
            factRelations: [{ factId: "fact-notice", role: "RELATED_TO", partyIds: ["party-acme"], note: "Notice fact also relates to damages timing." }],
            authorities: [
              {
                authorityId: "auth-synth-notice",
                citation: "SYNTHETIC-2D-2019-014",
                title: "Synthetic notice example",
                relation: "PERSUASIVE",
                treatment: "UNVERIFIED",
                currentness: "unknown",
                proposition: "Synthetic source span: notice defenses turn on recorded delivery facts.",
                sourceSpan: "Synthetic source span: notice defenses turn on recorded delivery facts.",
                sourceSupported: true,
                target: "defense",
                targetId: "def-notice",
              },
            ],
            standards: [],
            uncertainty: ["Delivery remains unresolved."],
            provenance: PROV("doc-answer", "Notice defense.", "plead-answer"),
          },
        ],
        evidence: [
          { evidenceId: "ev-log", role: "SUPPORTS", partyIds: ["party-acme"], note: null },
          { evidenceId: "ev-notice", role: "CONTRADICTS", partyIds: ["party-acme"], note: null },
        ],
        factRelations: [{ factId: "fact-notice", role: "RELATED_TO", partyIds: ["party-acme"], note: null }],
        authorities: [],
        standards: [],
        legalIssueIds: ["issue-notice"],
        uncertainty: [],
        provenance: PROV("doc-answer", "Notice defense.", "plead-answer"),
        validityConclusion: null,
      },
    ],
    legalIssues: [
      { issueId: "issue-breach", label: "Breach of supply agreement", claimIds: ["claim-breach", "claim-breach-v1"], defenseIds: ["def-no-breach"] },
      { issueId: "issue-damages", label: "Damages for breach", claimIds: ["claim-breach"], defenseIds: [] },
      { issueId: "issue-misrep", label: "Negligent misrepresentation (withdrawn)", claimIds: ["claim-negligent-misrep"], defenseIds: [] },
      { issueId: "issue-utp", label: "Statutory unfair-trade", claimIds: ["claim-unfair-trade"], defenseIds: ["def-notice"] },
      { issueId: "issue-counter", label: "Unpaid invoice counterclaim", claimIds: ["claim-counter-invoice"], defenseIds: [] },
      { issueId: "issue-waiver", label: "Waiver", claimIds: ["claim-breach"], defenseIds: ["def-waiver"] },
      { issueId: "issue-notice", label: "Notice", claimIds: ["claim-breach", "claim-unfair-trade"], defenseIds: ["def-notice"] },
    ],
    theories: [
      {
        id: "theory-plaintiff",
        orientation: "plaintiff",
        label: "River theory: notice-and-breach plus statutory unfair-trade",
        supportingFactIds: ["fact-contract", "fact-notice"],
        contraryFactIds: [],
        missingFactIds: ["missing-delivery"],
        affectedClaimIds: ["claim-breach", "claim-unfair-trade"],
        affectedDefenseIds: [],
        status: "hypothesis",
      },
      {
        id: "theory-defendant",
        orientation: "defendant",
        label: "Acme theory: performance, waiver, and notice failure",
        supportingFactIds: [],
        contraryFactIds: ["fact-notice"],
        missingFactIds: ["missing-waiver"],
        affectedClaimIds: ["claim-breach"],
        affectedDefenseIds: ["def-no-breach", "def-waiver", "def-notice"],
        status: "hypothesis",
      },
      {
        id: "theory-counter",
        orientation: "counterclaim",
        label: "Acme counterclaim theory: unpaid invoice",
        supportingFactIds: ["fact-invoice"],
        contraryFactIds: [],
        missingFactIds: [],
        affectedClaimIds: ["claim-counter-invoice"],
        affectedDefenseIds: [],
        status: "hypothesis",
      },
    ],
    coverageWarnings: [
      "Application-layer prototype only; not persisted to the database.",
      "Treatment remains UNVERIFIED unless a source marks it verified.",
    ],
    liabilityConclusion: null,
    outcomeConclusion: null,
  };

  const matrix = buildCivilClaimMatrix(review);
  const whole = buildCivilWholeMatterView(review);
  const askText = formatCivilClaimsAnswer(
    answerCivilClaimsQuestion({
      review,
      question: "What claims are currently pleaded and which breach elements are unsupported?",
    }),
  );

  return { review, matrix, whole, askText };
}
