import { enrichLedgerWithBatesSignals } from "./model";
import type { DiscoveryLedgerReview, DiscoveryProvenance } from "./types";

const PROV = (documentId: string, span: string): DiscoveryProvenance => ({
  documentId,
  sourceSpan: span,
  sourcePage: 1,
  humanEntered: false,
  extractionOrigin: "deterministic_fixture",
});

/**
 * Realistic Pass 4 fixture: River Co. vs Acme LLC discovery.
 * Includes RFP + interrogatories, objections, partial + supplemental production,
 * Bates overlap/gap signals, missing attachment, privilege assertion,
 * meet-and-confer, and motion-to-compel linkage.
 */
export function runComplexDiscoveryLedgerFixture(): {
  review: DiscoveryLedgerReview;
} {
  const review: DiscoveryLedgerReview = {
    matterId: "matter-discovery-d4",
    organizationId: "org-synthetic-firm",
    parties: [
      { partyId: "party-river", displayName: "River Co." },
      { partyId: "party-acme", displayName: "Acme LLC" },
    ],
    requestSets: [
      {
        id: "set-rfp-1",
        label: "Plaintiff's First Set of Requests for Production",
        discoveryType: "REQUEST_FOR_PRODUCTION",
        requestingPartyId: "party-river",
        respondingPartyId: "party-acme",
        servedAt: "2026-08-01",
        responseDueAt: "2026-08-31",
        isCurrent: true,
        supersededBySetId: null,
        sourceDocumentId: "doc-rfp-1",
        provenance: PROV("doc-rfp-1", "First Set RFPs caption and requests 1–15."),
      },
      {
        id: "set-rog-1",
        label: "Plaintiff's First Set of Interrogatories",
        discoveryType: "INTERROGATORY",
        requestingPartyId: "party-river",
        respondingPartyId: "party-acme",
        servedAt: "2026-08-01",
        responseDueAt: "2026-08-31",
        isCurrent: true,
        supersededBySetId: null,
        sourceDocumentId: "doc-rog-1",
        provenance: PROV("doc-rog-1", "First Set Interrogatories 1–10."),
      },
    ],
    items: [
      {
        id: "item-rfp-12",
        setId: "set-rfp-1",
        requestNumber: "RFP-12",
        title: "Cure-notice communications",
        requestText:
          "All documents and communications concerning cure notices sent by River Co. to Acme LLC regarding the 2025 Supply Agreement.",
        status: "PARTIALLY_RESPONDED",
        requestingPartyId: "party-river",
        respondingPartyId: "party-acme",
        servedAt: "2026-08-01",
        responseDueAt: "2026-08-31",
        provenance: PROV("doc-rfp-1", "Request No. 12."),
      },
      {
        id: "item-rfp-14",
        setId: "set-rfp-1",
        requestNumber: "RFP-14",
        title: "Invoice support files",
        requestText: "All invoices, packing slips, and payment records for shipments under the Supply Agreement.",
        status: "OBJECTED",
        requestingPartyId: "party-river",
        respondingPartyId: "party-acme",
        servedAt: "2026-08-01",
        responseDueAt: "2026-08-31",
        provenance: PROV("doc-rfp-1", "Request No. 14."),
      },
      {
        id: "item-rfp-15",
        setId: "set-rfp-1",
        requestNumber: "RFP-15",
        title: "Quality-control attachments",
        requestText: "Quality-control reports and attachments for Beta dock shipments.",
        status: "DEFICIENT",
        requestingPartyId: "party-river",
        respondingPartyId: "party-acme",
        servedAt: "2026-08-01",
        responseDueAt: "2026-08-31",
        provenance: PROV("doc-rfp-1", "Request No. 15."),
      },
      {
        id: "item-rog-3",
        setId: "set-rog-1",
        requestNumber: "ROG-3",
        title: "Persons with knowledge of notice",
        requestText: "Identify each person with knowledge of the August 2025 cure notice and delivery attempts.",
        status: "OPEN",
        requestingPartyId: "party-river",
        respondingPartyId: "party-acme",
        servedAt: "2026-08-01",
        responseDueAt: "2026-08-31",
        provenance: PROV("doc-rog-1", "Interrogatory No. 3."),
      },
    ],
    objections: [
      {
        id: "obj-14-undue",
        itemId: "item-rfp-14",
        responseId: "resp-14",
        basis: "undue burden",
        text: "Acme objects that Request No. 14 is unduly burdensome to the extent it seeks all packing slips.",
        provenance: PROV("doc-acme-responses", "Response to Request No. 14 — objections."),
      },
    ],
    responses: [
      {
        id: "resp-12",
        itemId: "item-rfp-12",
        label: "Acme Response to RFP-12",
        respondedAt: "2026-08-28",
        isSupplemental: false,
        supplementsResponseId: null,
        substantiveText: "Acme produces non-privileged documents Bates ACME000100–ACME000180 concerning cure notice correspondence.",
        objectionIds: [],
        productionIds: ["prod-1"],
        sourceDocumentId: "doc-acme-responses",
        provenance: PROV("doc-acme-responses", "Response to Request No. 12."),
      },
      {
        id: "resp-12-supp",
        itemId: "item-rfp-12",
        label: "Acme Supplemental Response to RFP-12",
        respondedAt: "2026-09-18",
        isSupplemental: true,
        supplementsResponseId: "resp-12",
        substantiveText: "Acme supplements with additional notice-delivery emails Bates ACME000200–ACME000220.",
        objectionIds: [],
        productionIds: ["prod-2"],
        sourceDocumentId: "doc-acme-supp",
        provenance: PROV("doc-acme-supp", "Supplemental response to Request No. 12."),
      },
      {
        id: "resp-14",
        itemId: "item-rfp-14",
        label: "Acme Response to RFP-14",
        respondedAt: "2026-08-28",
        isSupplemental: false,
        supplementsResponseId: null,
        substantiveText: null,
        objectionIds: ["obj-14-undue"],
        productionIds: [],
        sourceDocumentId: "doc-acme-responses",
        provenance: PROV("doc-acme-responses", "Response to Request No. 14."),
      },
      {
        id: "resp-15",
        itemId: "item-rfp-15",
        label: "Acme Response to RFP-15",
        respondedAt: "2026-08-28",
        isSupplemental: false,
        supplementsResponseId: null,
        substantiveText: "Acme produces QC report cover pages but states the Excel attachment is 'to follow.'",
        objectionIds: [],
        productionIds: ["prod-1"],
        sourceDocumentId: "doc-acme-responses",
        provenance: PROV("doc-acme-responses", "Response to Request No. 15."),
      },
    ],
    productions: [
      {
        id: "prod-1",
        label: "Acme Production Vol. 1",
        producingPartyId: "party-acme",
        receivingPartyId: "party-river",
        producedAt: "2026-08-28",
        isSupplemental: false,
        supplementsProductionId: null,
        transmittalDocumentId: "doc-prod-cover-1",
        documentIds: ["doc-notice-email", "doc-qc-cover"],
        evidenceIds: ["ev-notice"],
        custodianIds: ["custodian-jordan"],
        requestItemIds: ["item-rfp-12", "item-rfp-15"],
        notes: "Initial production; QC attachment referenced but not enclosed.",
        batesRanges: [
          {
            id: "bates-1a",
            productionId: "prod-1",
            prefix: "ACME",
            start: 100,
            end: 180,
            rawText: "ACME000100–ACME000180",
            provenance: PROV("doc-prod-cover-1", "Bates legend Vol. 1."),
          },
          {
            id: "bates-1b",
            productionId: "prod-1",
            prefix: "ACME",
            start: 150,
            end: 165,
            rawText: "ACME000150–ACME000165",
            provenance: PROV("doc-prod-cover-1", "Second listed range overlaps first."),
          },
        ],
        provenance: PROV("doc-prod-cover-1", "Production Vol. 1 transmittal."),
      },
      {
        id: "prod-2",
        label: "Acme Supplemental Production Vol. 2",
        producingPartyId: "party-acme",
        receivingPartyId: "party-river",
        producedAt: "2026-09-18",
        isSupplemental: true,
        supplementsProductionId: "prod-1",
        transmittalDocumentId: "doc-prod-cover-2",
        documentIds: ["doc-notice-followup"],
        evidenceIds: ["ev-notice"],
        custodianIds: ["custodian-jordan"],
        requestItemIds: ["item-rfp-12"],
        notes: "Supplemental notice emails; apparent Bates gap after Vol. 1.",
        batesRanges: [
          {
            id: "bates-2a",
            productionId: "prod-2",
            prefix: "ACME",
            start: 200,
            end: 220,
            rawText: "ACME000200–ACME000220",
            provenance: PROV("doc-prod-cover-2", "Bates legend Vol. 2."),
          },
        ],
        provenance: PROV("doc-prod-cover-2", "Supplemental production transmittal."),
      },
    ],
    deficiencies: [
      {
        id: "def-rog3",
        kind: "NO_RESPONSE",
        itemId: "item-rog-3",
        productionId: null,
        description: "Interrogatory No. 3 remains unanswered after the stated response date.",
        status: "OPEN",
        openedAt: "2026-09-01",
        responsiblePartyId: "party-acme",
        communicationId: null,
        meetAndConferId: "mac-1",
        motionId: "motion-compel-1",
        isReviewSignal: false,
        provenance: PROV("doc-rfp-1", "ROG-3 outstanding tracking."),
      },
      {
        id: "def-rfp14",
        kind: "OBJECTION_ONLY",
        itemId: "item-rfp-14",
        productionId: null,
        description: "Request No. 14 has objections and no substantive production.",
        status: "MEET_AND_CONFER",
        openedAt: "2026-09-01",
        responsiblePartyId: "party-acme",
        communicationId: "comm-mac-letter",
        meetAndConferId: "mac-1",
        motionId: "motion-compel-1",
        isReviewSignal: false,
        provenance: PROV("doc-acme-responses", "RFP-14 objection-only."),
      },
      {
        id: "def-rfp15-attach",
        kind: "MISSING_ATTACHMENT",
        itemId: "item-rfp-15",
        productionId: "prod-1",
        description: "QC Excel attachment referenced in response to RFP-15 is not in Production Vol. 1.",
        status: "OPEN",
        openedAt: "2026-08-29",
        responsiblePartyId: "party-acme",
        communicationId: null,
        meetAndConferId: "mac-1",
        motionId: null,
        isReviewSignal: false,
        provenance: PROV("doc-acme-responses", "RFP-15 attachment to follow."),
      },
      {
        id: "def-bates-gap",
        kind: "BATES_GAP",
        itemId: null,
        productionId: "prod-2",
        description: "Apparent Bates gap between ACME000180 and ACME000200 across productions (review signal).",
        status: "OPEN",
        openedAt: "2026-09-18",
        responsiblePartyId: "party-acme",
        communicationId: null,
        meetAndConferId: null,
        motionId: null,
        isReviewSignal: true,
        provenance: PROV("doc-prod-cover-2", "Bates sequence observation."),
      },
    ],
    privilegeAssertions: [
      {
        id: "priv-1",
        status: "ASSERTED",
        assertedBasis: "attorney-client communication",
        assertingPartyId: "party-acme",
        assertedAt: "2026-08-28",
        documentId: "doc-counsel-email",
        evidenceId: null,
        productionId: "prod-1",
        privilegeLogDocumentId: "doc-privilege-log",
        reviewNotes: "Listed on Acme privilege log entry 4; human review pending.",
        courtRulingReferenced: false,
        provenance: PROV("doc-privilege-log", "Privilege log entry 4."),
      },
    ],
    meetAndConferIssues: [
      {
        id: "mac-1",
        label: "September 5 meet-and-confer on RFP-14/ROG-3/RFP-15 attachment",
        deficiencyIds: ["def-rog3", "def-rfp14", "def-rfp15-attach"],
        communicationId: "comm-mac-letter",
        occurredAt: "2026-09-05",
        outcomeNotes: "Acme agreed to reconsider RFP-14 burden objection; ROG-3 still outstanding.",
        provenance: PROV("doc-mac-letter", "Meet-and-confer summary letter."),
      },
    ],
    motionLinks: [
      {
        id: "motion-link-1",
        motionId: "motion-compel-1",
        motionLabel: "River Motion to Compel Discovery Responses",
        motionType: "MOTION_TO_COMPEL",
        deficiencyIds: ["def-rog3", "def-rfp14"],
        documentId: "doc-motion-compel",
      },
    ],
    batesSignals: [],
    coverageWarnings: [
      "Synthetic discovery fixture for Deepening Pass 4; not a real matter.",
      "Existing Phase 5 document_review_states remain separate from this ledger prototype.",
    ],
    sanctionsConclusion: null,
    privilegeLegalConclusion: null,
  };

  return { review: enrichLedgerWithBatesSignals(review) };
}

/** Scale fixture for performance review signals (100+ request items). */
export function runLargeDiscoveryLedgerFixture(itemCount = 120): {
  review: DiscoveryLedgerReview;
} {
  const base = runComplexDiscoveryLedgerFixture().review;
  const items = [...base.items];
  for (let i = 1; i <= itemCount; i += 1) {
    items.push({
      id: `item-scale-rfp-${i}`,
      setId: "set-rfp-1",
      requestNumber: `RFP-S${i}`,
      title: `Scale request ${i}`,
      requestText: `Produce documents responsive to scale request ${i}.`,
      status: i % 17 === 0 ? "OPEN" : i % 11 === 0 ? "OBJECTED" : "RESPONDED",
      requestingPartyId: "party-river",
      respondingPartyId: "party-acme",
      servedAt: "2026-08-01",
      responseDueAt: "2026-08-31",
      provenance: PROV("doc-rfp-1", `Scale request ${i}.`),
    });
  }
  return {
    review: enrichLedgerWithBatesSignals({
      ...base,
      items,
      coverageWarnings: [
        ...base.coverageWarnings,
        `Scale fixture generated ${itemCount} additional synthetic request items.`,
      ],
    }),
  };
}
