ALTER TABLE "prosecution_officers" DROP CONSTRAINT IF EXISTS "prosecution_officers_case_org_fk";
ALTER TABLE "prosecution_hearings" DROP CONSTRAINT IF EXISTS "prosecution_hearings_case_org_fk";
ALTER TABLE "prosecution_motions" DROP CONSTRAINT IF EXISTS "prosecution_motions_case_org_fk";
ALTER TABLE "prosecution_warrants" DROP CONSTRAINT IF EXISTS "prosecution_warrants_case_org_fk";
ALTER TABLE "prosecution_procedure_issues" DROP CONSTRAINT IF EXISTS "prosecution_procedure_issues_case_org_fk";
ALTER TABLE "prosecution_disclosure_candidates" DROP CONSTRAINT IF EXISTS "prosecution_disclosure_candidates_case_org_fk";
ALTER TABLE "prosecution_discovery_items" DROP CONSTRAINT IF EXISTS "prosecution_discovery_items_case_org_fk";
ALTER TABLE "prosecution_witness_statements" DROP CONSTRAINT IF EXISTS "prosecution_witness_statements_witness_case_fk";
ALTER TABLE "prosecution_witness_statements" DROP CONSTRAINT IF EXISTS "prosecution_witness_statements_case_org_fk";
ALTER TABLE "prosecution_witnesses" DROP CONSTRAINT IF EXISTS "prosecution_witnesses_case_org_fk";
ALTER TABLE "prosecution_evidence_links" DROP CONSTRAINT IF EXISTS "prosecution_evidence_links_evidence_case_fk";
ALTER TABLE "prosecution_evidence_links" DROP CONSTRAINT IF EXISTS "prosecution_evidence_links_case_org_fk";
ALTER TABLE "prosecution_evidence_items" DROP CONSTRAINT IF EXISTS "prosecution_evidence_items_case_org_fk";
ALTER TABLE "prosecution_charge_elements" DROP CONSTRAINT IF EXISTS "prosecution_charge_elements_charge_case_fk";
ALTER TABLE "prosecution_charge_elements" DROP CONSTRAINT IF EXISTS "prosecution_charge_elements_case_org_fk";
ALTER TABLE "prosecution_charges" DROP CONSTRAINT IF EXISTS "prosecution_charges_defendant_case_fk";
ALTER TABLE "prosecution_charges" DROP CONSTRAINT IF EXISTS "prosecution_charges_case_org_fk";
ALTER TABLE "prosecution_defendants" DROP CONSTRAINT IF EXISTS "prosecution_defendants_case_org_fk";
DROP INDEX IF EXISTS "prosecution_witnesses_id_case_uidx";
DROP INDEX IF EXISTS "prosecution_evidence_items_id_case_uidx";
DROP INDEX IF EXISTS "prosecution_charges_id_case_uidx";
DROP INDEX IF EXISTS "prosecution_defendants_id_case_uidx";
DROP INDEX IF EXISTS "criminal_cases_id_org_uidx";
