import { evaluateAuthorityStatus } from "@nyayagrid/jurisdiction";
import type { SourceProvenance } from "../legal/types";
import { ProsecutionWorkspace } from "./memory";

const provenance = (extra: Partial<SourceProvenance> = {}): SourceProvenance => ({
  extractionOrigin: "deterministic_fixture",
  documentId: "doc-synthetic-report",
  sourceSpan: "Synthetic source span.",
  sourcePage: 1,
  ...extra,
});

/** Prosecutor demo. Synthetic facts only. The matrix never returns a guilt verdict. */
export function buildProsecutorDemo(): ProsecutionWorkspace {
  const workspace = new ProsecutionWorkspace();
  const organizationId = "org-synthetic-prosecution";
  const criminalCase = workspace.createCase({
    organizationId,
    matterId: null,
    caseNumber: "SYN-CR-1001",
    jurisdiction: "PA",
    court: "st-pa-trial",
    courthouse: "Synthetic Courthouse",
    caseStatus: "open",
    assignedProsecutorId: "user-prosecutor",
    supervisingProsecutorId: "user-supervisor",
    investigatingAgencyId: null,
    priority: "normal",
    filingDate: "2026-03-01",
    arrestDate: "2026-02-20",
    offenseDateStart: "2026-02-18",
    offenseDateEnd: "2026-02-18",
    trialDate: null,
    sentencingDate: null,
    closedDate: null,
    summary: "Synthetic prosecution fixture.",
    notes: null,
    createdByUserId: "user-prosecutor",
    updatedByUserId: "user-prosecutor",
  });
  const agency = workspace.addAgency({
    organizationId,
    name: "Synthetic Police Department",
    agencyType: "police",
    jurisdiction: "PA",
    contact: { phone: "000-000-0000" },
  });
  const defendant = workspace.addDefendant({
    organizationId,
    criminalCaseId: criminalCase.id,
    displayName: "Synthetic Defendant",
    aliases: [],
    dateOfBirth: null,
    custodyStatus: "released",
    defenseCounsel: "Synthetic Counsel",
    notes: null,
    status: "active",
    provenance: provenance(),
    privacy: { dobRestricted: true },
  });
  const officer = workspace.addOfficer({
    organizationId,
    criminalCaseId: criminalCase.id,
    agencyId: agency.id,
    name: "Synthetic Officer",
    role: "investigator",
    badgeIdentifier: "SYN-1",
    reportIds: [],
    interviewIds: [],
    warrantIds: [],
    evidenceCollectedIds: [],
    testimonyIds: [],
  });
  const report = workspace.addEvidence({
    organizationId,
    criminalCaseId: criminalCase.id,
    documentId: "doc-synthetic-report",
    evidenceType: "police_report",
    sourceAgency: agency.id,
    collector: officer.id,
    collectionDate: "2026-02-19",
    storageReference: "SYN-EV-1",
    chainOfCustody: ["collected", "logged"],
    relatedDefendantIds: [defendant.id],
    relatedChargeIds: [],
    relatedElementIds: [],
    relatedWitnessIds: [],
    sensitivity: "standard",
    reviewStatus: "received",
    provenance: provenance(),
  });
  const physical = workspace.addEvidence({
    organizationId,
    criminalCaseId: criminalCase.id,
    documentId: "doc-synthetic-property",
    evidenceType: "physical",
    sourceAgency: agency.id,
    collector: officer.id,
    collectionDate: "2026-02-19",
    storageReference: "SYN-EV-2",
    chainOfCustody: ["seized"],
    relatedDefendantIds: [defendant.id],
    relatedChargeIds: [],
    relatedElementIds: [],
    relatedWitnessIds: [],
    sensitivity: "standard",
    reviewStatus: "received",
    provenance: provenance({ documentId: "doc-synthetic-property" }),
  });
  const theft = workspace.addCharge({
    organizationId,
    criminalCaseId: criminalCase.id,
    defendantId: defendant.id,
    countNumber: "1",
    statuteAuthorityId: "auth-synthetic-statute",
    statuteCitation: "SYNTHETIC-STATUTE-1",
    offenseName: "Synthetic theft count",
    offenseClassification: "misdemeanor",
    jurisdiction: "PA",
    filingDate: "2026-03-01",
    status: "pending",
    amendmentHistory: [],
    dispositionId: null,
    provenance: provenance({ authorityId: "auth-synthetic-statute" }),
  });
  const receiving = workspace.addCharge({
    organizationId,
    criminalCaseId: criminalCase.id,
    defendantId: defendant.id,
    countNumber: "2",
    statuteAuthorityId: "auth-synthetic-statute",
    statuteCitation: "SYNTHETIC-STATUTE-2",
    offenseName: "Synthetic receiving count",
    offenseClassification: "misdemeanor",
    jurisdiction: "PA",
    filingDate: "2026-03-01",
    status: "pending",
    amendmentHistory: [],
    dispositionId: null,
    provenance: provenance({ authorityId: "auth-synthetic-statute" }),
  });
  const taking = workspace.addElement({
    organizationId,
    criminalCaseId: criminalCase.id,
    chargeId: theft.id,
    elementOrder: 1,
    elementText: "Taking",
    elementType: "element",
    legalStandardId: null,
    supportingEvidenceIds: [report.id],
    contraryEvidenceIds: [],
    uncertainEvidenceIds: [],
    missingEvidenceIds: [],
    relatedAuthorityIds: ["auth-synthetic-statute"],
    confidence: "medium",
    humanReviewStatus: "unreviewed",
    provenance: provenance(),
  });
  workspace.addElement({
    organizationId,
    criminalCaseId: criminalCase.id,
    chargeId: theft.id,
    elementOrder: 2,
    elementText: "Intent",
    elementType: "element",
    legalStandardId: null,
    supportingEvidenceIds: [report.id],
    contraryEvidenceIds: ["stmt-contrary"],
    uncertainEvidenceIds: [],
    missingEvidenceIds: [],
    relatedAuthorityIds: ["auth-synthetic-case"],
    confidence: "low",
    humanReviewStatus: "unreviewed",
    provenance: provenance(),
  });
  workspace.addElement({
    organizationId,
    criminalCaseId: criminalCase.id,
    chargeId: receiving.id,
    elementOrder: 1,
    elementText: "Knowledge the property was stolen",
    elementType: "element",
    legalStandardId: null,
    supportingEvidenceIds: [],
    contraryEvidenceIds: [],
    uncertainEvidenceIds: [],
    missingEvidenceIds: ["knowledge-source"],
    relatedAuthorityIds: ["auth-synthetic-statute"],
    confidence: "low",
    humanReviewStatus: "unreviewed",
    provenance: provenance(),
  });
  workspace.linkEvidence({
    organizationId,
    criminalCaseId: criminalCase.id,
    evidenceId: report.id,
    relationship: "SUPPORTS_ELEMENT",
    targetType: "ChargeElement",
    targetId: taking.id,
    provenance: provenance(),
  });
  workspace.linkEvidence({
    organizationId,
    criminalCaseId: criminalCase.id,
    evidenceId: physical.id,
    relationship: "CORROBORATES",
    targetType: "Charge",
    targetId: theft.id,
    provenance: provenance({ documentId: "doc-synthetic-property" }),
  });
  const witness = workspace.addWitness({
    organizationId,
    criminalCaseId: criminalCase.id,
    entityId: null,
    displayName: "Synthetic Witness",
    witnessType: "civilian",
    relationship: "bystander",
    statementIds: [],
    testimonyIds: [],
    relatedEvidenceIds: [report.id],
    notes: null,
    sensitivity: "standard",
    provenance: provenance(),
  });
  workspace.addStatement({
    id: "stmt-a",
    organizationId,
    criminalCaseId: criminalCase.id,
    witnessId: witness.id,
    statementDate: "2026-02-19",
    statementType: "interview",
    sourceDocumentId: "doc-synthetic-report",
    sourceSpan: "Witness said the person left with the item.",
    interviewer: officer.id,
    eventContext: "station interview",
    claims: [{ key: "took-item", value: "yes", kind: "fact" }],
    confidence: "medium",
    provenance: provenance(),
  });
  workspace.addStatement({
    id: "stmt-contrary",
    organizationId,
    criminalCaseId: criminalCase.id,
    witnessId: witness.id,
    statementDate: "2026-02-21",
    statementType: "interview",
    sourceDocumentId: "doc-synthetic-followup",
    sourceSpan: "Witness said they did not see a taking.",
    interviewer: officer.id,
    eventContext: "follow-up",
    claims: [{ key: "took-item", value: "no", kind: "fact" }],
    confidence: "medium",
    provenance: provenance({ documentId: "doc-synthetic-followup" }),
  });
  workspace.addDiscovery({
    organizationId,
    criminalCaseId: criminalCase.id,
    source: "police",
    category: "reports",
    receivedDate: "2026-02-22",
    reviewStatus: "RECEIVED",
    productionStatus: "RECEIVED",
    producedDate: null,
    relatedDocumentIds: ["doc-synthetic-report"],
    relatedEvidenceIds: [report.id],
    disclosureReviewStatus: "UNREVIEWED",
    notes: null,
    auditHistory: ["received"],
    provenance: provenance(),
  });
  workspace.addDisclosure({
    organizationId,
    criminalCaseId: criminalCase.id,
    category: "PRIOR_INCONSISTENT_STATEMENT",
    status: "REVIEW_REQUIRED",
    notes: "Second statement conflicts with the first. Human review required.",
    humanActorId: null,
    provenance: provenance({ documentId: "doc-synthetic-followup" }),
  });
  const suppression = workspace.addProcedureIssue({
    organizationId,
    criminalCaseId: criminalCase.id,
    issueType: "WARRANT",
    relatedFactIds: [],
    relatedEvidenceIds: [physical.id],
    relatedAuthorityIds: ["auth-synthetic-case"],
    missingFacts: ["warrant return"],
    status: "open",
    confidence: "low",
    provenance: provenance({ documentId: "doc-synthetic-property" }),
  });
  workspace.addWarrant({
    organizationId,
    criminalCaseId: criminalCase.id,
    warrantType: "search",
    issuingCourt: "st-pa-trial",
    issuingJudge: null,
    applicationDate: "2026-02-18",
    issueDate: "2026-02-18",
    executionDate: "2026-02-19",
    scope: "Synthetic premises",
    probableCauseFacts: ["Synthetic affidavit fact"],
    sourceFactIds: [],
    seizedEvidenceIds: [physical.id],
    returnNotes: null,
    relatedSuppressionIssueIds: [suppression.id],
    provenance: provenance(),
  });
  workspace.addTimeline({
    organizationId,
    criminalCaseId: criminalCase.id,
    matterId: null,
    eventType: "CHARGE_FILED",
    title: "Counts filed",
    eventDate: "2026-03-01",
    provenance: provenance(),
  });
  workspace.addTask({
    organizationId,
    criminalCaseId: criminalCase.id,
    title: "Review inconsistent statement",
    status: "open",
    dueAt: null,
  });
  const authority = evaluateAuthorityStatus({
    questionJurisdiction: "PA",
    forumCourtId: "st-pa-trial",
    issueType: "STATE_LAW",
    subjectMatter: "criminal",
    authorityCourtId: "st-pa-high",
  });
  return Object.assign(workspace, { syntheticAuthorityStatus: authority });
}
