/** Generated from certified Neon holding screen. Propositions are source spans only. */
export const SOURCE_BACKED_SUPPRESSION_AUTHORITIES = [
  {
    "caseName": "Illinois v. Gates",
    "citation": "462 U.S. 213",
    "authorityId": "83949afa-33e2-4cec-8fe5-1e7b0138eef9",
    "courtId": "us-scotus",
    "jurisdiction": "US",
    "dimension": "PROBABLE_CAUSE",
    "doctrine": "FEDERAL_CONSTITUTIONAL",
    "proposition": "totality-of-the-circumstances approach",
    "sourceSpan": " “probable cause” to believe that contraband or evidence is located in a particular place. Ill This totality-of-the-circumstances approach is far more consistent with our prior treatment of probable cause 6 than *231 is any rigid demand that specific “tests” be satisfied by every informant’s tip. ",
    "sourceText": " “probable cause” to believe that contraband or evidence is located in a particular place. Ill This totality-of-the-circumstances approach is far more consistent with our prior treatment of probable cause 6 than *231 is any rigid demand that specific “tests” be satisfied by every informant’s tip. ",
    "treatment": "UNVERIFIED",
    "treatmentVerification": "unknown",
    "currentnessStatus": "historical",
    "canonicalSourceUrl": "https://www.courtlistener.com/opinion/110959/illinois-v-gates/",
    "persuasiveOnly": false,
    "note": null,
    "sourceSupported": true,
    "autoAttach": true
  },
  {
    "caseName": "United States v. Leon",
    "citation": "468 U.S. 897",
    "authorityId": "c494cde9-c897-4bb4-a920-b7ea085fb468",
    "courtId": "us-scotus",
    "jurisdiction": "US",
    "dimension": "GOOD_FAITH",
    "doctrine": "FEDERAL_CONSTITUTIONAL",
    "proposition": "“good faith” exception",
    "sourceSpan": "urth Amendment, and another in which there is grave doubt on the question, in order to promulgate a “good faith” exception to the Fourth Amendment’s exclusionary rule. The Court’s explanation for its failure to decide the merits of the Fourth Amendment question in No. 82-963 is tha",
    "sourceText": "urth Amendment, and another in which there is grave doubt on the question, in order to promulgate a “good faith” exception to the Fourth Amendment’s exclusionary rule. The Court’s explanation for its failure to decide the merits of the Fourth Amendment question in No. 82-963 is tha",
    "treatment": "UNVERIFIED",
    "treatmentVerification": "unknown",
    "currentnessStatus": "historical",
    "canonicalSourceUrl": "https://www.courtlistener.com/opinion/111262/united-states-v-leon/",
    "persuasiveOnly": false,
    "note": null,
    "sourceSupported": true,
    "autoAttach": true
  },
  {
    "caseName": "Welsh v. Wisconsin",
    "citation": "466 U.S. 740",
    "authorityId": "f6fac4af-1858-4098-9a36-12cfeca6649c",
    "courtId": "us-scotus",
    "jurisdiction": "US",
    "dimension": "EXIGENCY",
    "doctrine": "FEDERAL_CONSTITUTIONAL",
    "proposition": "exigent circumstances",
    "sourceSpan": "pinion of the Court. Payton v. New York, 445 U. S. 573 (1980), held that, absent probable cause and exigent circumstances, warrantless arrests in the home are prohibited by the Fourth Amend *742 ment. But the Court in that case explicitly refused “to consider the sort of emergency",
    "sourceText": "pinion of the Court. Payton v. New York, 445 U. S. 573 (1980), held that, absent probable cause and exigent circumstances, warrantless arrests in the home are prohibited by the Fourth Amend *742 ment. But the Court in that case explicitly refused “to consider the sort of emergency",
    "treatment": "UNVERIFIED",
    "treatmentVerification": "unknown",
    "currentnessStatus": "historical",
    "canonicalSourceUrl": "https://www.courtlistener.com/opinion/111173/",
    "persuasiveOnly": false,
    "note": null,
    "sourceSupported": true,
    "autoAttach": true
  },
  {
    "caseName": "Hudson v. Michigan",
    "citation": "547 U.S. 586",
    "authorityId": "9fe84e04-d4dc-4aaa-b75f-c4ec005100dc",
    "courtId": "us-scotus",
    "jurisdiction": "US",
    "dimension": "EXECUTION",
    "doctrine": "FEDERAL_CONSTITUTIONAL",
    "proposition": "knock-and-announce",
    "sourceSpan": "for narcotics and weapons entered petitioner Hudson’s home in violation of the Fourth Amend ment’s “knock-and-announce” rule. The trial court granted Hudson’s motion to suppress the evidence seized, but the Michigan Court of Appeals reversed on interlocutory appeal. Hudson was ",
    "sourceText": "for narcotics and weapons entered petitioner Hudson’s home in violation of the Fourth Amend ment’s “knock-and-announce” rule. The trial court granted Hudson’s motion to suppress the evidence seized, but the Michigan Court of Appeals reversed on interlocutory appeal. Hudson was ",
    "treatment": "UNVERIFIED",
    "treatmentVerification": "unknown",
    "currentnessStatus": "historical",
    "canonicalSourceUrl": "https://www.courtlistener.com/opinion/145646/",
    "persuasiveOnly": false,
    "note": null,
    "sourceSupported": true,
    "autoAttach": true
  },
  {
    "caseName": "Davis v. United States",
    "citation": "564 U.S. 229",
    "authorityId": "e67d1763-da45-4c07-b2e8-625309542a1f",
    "courtId": "us-scotus",
    "jurisdiction": "US",
    "dimension": "GOOD_FAITH",
    "doctrine": "FEDERAL_CONSTITUTIONAL",
    "proposition": "searches conducted in objectively reasonable reliance on binding appellate precedent are not subject to the exclusionary rule",
    "sourceSpan": "ces, and because it would come at a high cost to both the truth and the public safety, we hold that searches conducted in objectively reasonable reliance on binding appellate precedent are not subject to the exclusionary rule. I The question presented arises in this case as a result of a shift in our Fourth Amendment jurisprudence on searches of automobiles incident to arrests of re",
    "sourceText": "ces, and because it would come at a high cost to both the truth and the public safety, we hold that searches conducted in objectively reasonable reliance on binding appellate precedent are not subject to the exclusionary rule. I The question presented arises in this case as a result of a shift in our Fourth Amendment jurisprudence on searches of automobiles incident to arrests of re",
    "treatment": "UNVERIFIED",
    "treatmentVerification": "unknown",
    "currentnessStatus": "historical",
    "canonicalSourceUrl": "https://www.courtlistener.com/opinion/7345713/",
    "persuasiveOnly": false,
    "note": null,
    "sourceSupported": true,
    "autoAttach": true
  },
  {
    "caseName": "Kentucky v. King",
    "citation": "563 U.S. 452",
    "authorityId": "b8cfd34d-53f1-4be1-a8ae-4deb904ff1a5",
    "courtId": "us-scotus",
    "jurisdiction": "US",
    "dimension": "EXIGENCY",
    "doctrine": "FEDERAL_CONSTITUTIONAL",
    "proposition": "exigent circumstances",
    "sourceSpan": ". This case involves a principal exception to the warrant requirement, the exception applicable in “exigent circumstances.” See ante, at 460. “[CJarefully delineated,” the exception should govern only in genuine emergency situations. Circumstances qualify as “exigent” when there i",
    "sourceText": ". This case involves a principal exception to the warrant requirement, the exception applicable in “exigent circumstances.” See ante, at 460. “[CJarefully delineated,” the exception should govern only in genuine emergency situations. Circumstances qualify as “exigent” when there i",
    "treatment": "UNVERIFIED",
    "treatmentVerification": "unknown",
    "currentnessStatus": "historical",
    "canonicalSourceUrl": "https://www.courtlistener.com/opinion/216733/kentucky-v-king/",
    "persuasiveOnly": false,
    "note": null,
    "sourceSupported": true,
    "autoAttach": true
  },
  {
    "caseName": "Pennsylvania Board of Probation & Parole v. Scott",
    "citation": "524 U.S. 357",
    "authorityId": "255d3085-72dc-4e87-a5bc-56f7f8dd18f3",
    "courtId": "us-scotus",
    "jurisdiction": "US",
    "dimension": "OTHER",
    "doctrine": "FEDERAL_CONSTITUTIONAL",
    "proposition": "exclusionary rule",
    "sourceSpan": "ableness of searches by parole officers. 668 A. 2d 590, 596 (1995). The court further held that the exclusionary rule should apply because, in the circumstances of respondent’s case, the deterrence benefits of the rule outweighed its costs. Id., at 600 . 2 The Pennsylvania Sup",
    "sourceText": "ableness of searches by parole officers. 668 A. 2d 590, 596 (1995). The court further held that the exclusionary rule should apply because, in the circumstances of respondent’s case, the deterrence benefits of the rule outweighed its costs. Id., at 600 . 2 The Pennsylvania Sup",
    "treatment": "UNVERIFIED",
    "treatmentVerification": "unknown",
    "currentnessStatus": "historical",
    "canonicalSourceUrl": "https://www.courtlistener.com/opinion/118235/",
    "persuasiveOnly": false,
    "note": "Parole/exclusionary context; not a standard warrant-dimension holding.",
    "sourceSupported": true,
    "autoAttach": false
  },
  {
    "caseName": "Beck v. Ohio",
    "citation": "379 U.S. 89",
    "authorityId": "9d5f025e-aea1-4e90-9331-3f24bde88429",
    "courtId": "us-scotus",
    "jurisdiction": "US",
    "dimension": "PROBABLE_CAUSE",
    "doctrine": "FEDERAL_CONSTITUTIONAL",
    "proposition": "probable cause to make it",
    "sourceSpan": "itutionally valid depends in turn upon whether, at the moment the arrest was made, the officers had probable cause to make itwhether at that moment the facts and circumstances within their knowledge and of which they had reasonably trustworthy information were sufficient to warrant a",
    "sourceText": "itutionally valid depends in turn upon whether, at the moment the arrest was made, the officers had probable cause to make itwhether at that moment the facts and circumstances within their knowledge and of which they had reasonably trustworthy information were sufficient to warrant a",
    "treatment": "UNVERIFIED",
    "treatmentVerification": "unknown",
    "currentnessStatus": "unknown",
    "canonicalSourceUrl": "https://www.courtlistener.com/opinion/106936/",
    "persuasiveOnly": false,
    "note": null,
    "sourceSupported": true,
    "autoAttach": false
  },
  {
    "caseName": "Henry v. United States",
    "citation": "361 U.S. 98",
    "authorityId": "f1298c51-3bd9-47d7-8aba-a3a983da61c0",
    "courtId": "us-scotus",
    "jurisdiction": "US",
    "dimension": "PROBABLE_CAUSE",
    "doctrine": "FEDERAL_CONSTITUTIONAL",
    "proposition": "probable cause for the arrest",
    "sourceSpan": "len from an interstate shipment. See 18 U. S. C. § 659 . The issue in the case is whether there was probable cause for the arrest leading to the search that produced the evidence on which the conviction rests. A timely motion to suppress the evidence was made by *99 petitioner and overrul",
    "sourceText": "len from an interstate shipment. See 18 U. S. C. § 659 . The issue in the case is whether there was probable cause for the arrest leading to the search that produced the evidence on which the conviction rests. A timely motion to suppress the evidence was made by *99 petitioner and overrul",
    "treatment": "UNVERIFIED",
    "treatmentVerification": "unknown",
    "currentnessStatus": "unknown",
    "canonicalSourceUrl": "https://www.courtlistener.com/opinion/105963/",
    "persuasiveOnly": false,
    "note": null,
    "sourceSupported": true,
    "autoAttach": false
  },
  {
    "caseName": "United States v. Tracey",
    "citation": "597 F.3d 140",
    "authorityId": "37442c0b-fd17-4528-a929-515d6e1c2a0e",
    "courtId": "us-ca-3",
    "jurisdiction": "US",
    "dimension": "GOOD_FAITH",
    "doctrine": "FEDERAL_CONSTITUTIONAL",
    "proposition": "good faith",
    "sourceSpan": "sonably objective police officer would have recognized that the warrant was defective, and thus the good faith exception to the exclusionary rule did not apply. On appeal, the Government argues that the warrant was not general because it incorporated the narrower affida",
    "sourceText": "sonably objective police officer would have recognized that the warrant was defective, and thus the good faith exception to the exclusionary rule did not apply. On appeal, the Government argues that the warrant was not general because it incorporated the narrower affida",
    "treatment": "UNVERIFIED",
    "treatmentVerification": "unknown",
    "currentnessStatus": "unknown",
    "canonicalSourceUrl": "https://www.courtlistener.com/opinion/62/",
    "persuasiveOnly": false,
    "note": null,
    "sourceSupported": true,
    "autoAttach": true
  },
  {
    "caseName": "United States v. Katzin",
    "citation": "769 F.3d 163",
    "authorityId": "5b443a32-2dd0-4aef-858b-8490b43caa1e",
    "courtId": "us-ca-3",
    "jurisdiction": "US",
    "dimension": "GOOD_FAITH",
    "doctrine": "FEDERAL_CONSTITUTIONAL",
    "proposition": "good faith",
    "sourceSpan": "ectively ending the Government’s prosecution. We conclude that the evidence is admissible under the good faith 5 exception to the exclusionary rule and reverse the District Court’s grant of Appellees’ suppression motions. I. BACKGROUND In 2009 and 2010, the FBI and loca",
    "sourceText": "ectively ending the Government’s prosecution. We conclude that the evidence is admissible under the good faith 5 exception to the exclusionary rule and reverse the District Court’s grant of Appellees’ suppression motions. I. BACKGROUND In 2009 and 2010, the FBI and loca",
    "treatment": "UNVERIFIED",
    "treatmentVerification": "unknown",
    "currentnessStatus": "unknown",
    "canonicalSourceUrl": "https://www.courtlistener.com/opinion/2738861/",
    "persuasiveOnly": false,
    "note": null,
    "sourceSupported": true,
    "autoAttach": true
  },
  {
    "caseName": "United States v. Vasquez-Algarin",
    "citation": "821 F.3d 467",
    "authorityId": "07d6e7fb-d887-4e9f-8af7-121539e261b2",
    "courtId": "us-ca-3",
    "jurisdiction": "US",
    "dimension": "SCOPE",
    "doctrine": "FEDERAL_CONSTITUTIONAL",
    "proposition": "arrest warrant and a search warrant",
    "sourceSpan": "_ OPINION OF THE COURT _______________ KRAUSE, Circuit Judge. Law enforcement officers need both an arrest warrant and a search warrant to apprehend a suspect at what they know to be a third party’s home. If the suspect resides at the address in question, however, officers need only an arrest w",
    "sourceText": "_ OPINION OF THE COURT _______________ KRAUSE, Circuit Judge. Law enforcement officers need both an arrest warrant and a search warrant to apprehend a suspect at what they know to be a third party’s home. If the suspect resides at the address in question, however, officers need only an arrest w",
    "treatment": "UNVERIFIED",
    "treatmentVerification": "unknown",
    "currentnessStatus": "unknown",
    "canonicalSourceUrl": "https://www.courtlistener.com/opinion/3199633/",
    "persuasiveOnly": false,
    "note": null,
    "sourceSupported": true,
    "autoAttach": true
  },
  {
    "caseName": "United States v. Wright",
    "citation": "777 F.3d 635",
    "authorityId": "08399051-449b-47da-a266-ca68f4d8c016",
    "courtId": "us-ca-3",
    "jurisdiction": "US",
    "dimension": "EXECUTION",
    "doctrine": "FEDERAL_CONSTITUTIONAL",
    "proposition": "valid search warrant",
    "sourceSpan": "confronted the question of whether suppression is required when a law enforcement officer obtains a valid search warrant but mistakenly interprets a judge’s sealing order as prohibiting him from showing the list of items to be seized to the person whose property is being searched",
    "sourceText": "confronted the question of whether suppression is required when a law enforcement officer obtains a valid search warrant but mistakenly interprets a judge’s sealing order as prohibiting him from showing the list of items to be seized to the person whose property is being searched",
    "treatment": "UNVERIFIED",
    "treatmentVerification": "unknown",
    "currentnessStatus": "unknown",
    "canonicalSourceUrl": "https://www.courtlistener.com/opinion/2777610/",
    "persuasiveOnly": false,
    "note": null,
    "sourceSupported": true,
    "autoAttach": true
  },
  {
    "caseName": "In re Search Warrant No. 16-960-M-1 to Google",
    "citation": "275 F.Supp.3d 605",
    "authorityId": "40e6b507-2a06-4152-8df8-df4cb35615a3",
    "courtId": "us-d-pa-ed",
    "jurisdiction": "US",
    "dimension": "PARTICULARITY",
    "doctrine": "FEDERAL_CONSTITUTIONAL",
    "proposition": "Stored Communications Act",
    "sourceSpan": "ment’s motions to compel Google to fully comply with two warrants .issued pursuant to § 2703 of the Stored Communications Act (SCA), 18 U.S.C. §§ 2701-2712 . The warrants require Google to disclose to the Federal Bureau of Investigation electronic communications and other records and ",
    "sourceText": "ment’s motions to compel Google to fully comply with two warrants .issued pursuant to § 2703 of the Stored Communications Act (SCA), 18 U.S.C. §§ 2701-2712 . The warrants require Google to disclose to the Federal Bureau of Investigation electronic communications and other records and ",
    "treatment": "UNVERIFIED",
    "treatmentVerification": "unknown",
    "currentnessStatus": "unknown",
    "canonicalSourceUrl": "https://www.courtlistener.com/opinion/7327348/",
    "persuasiveOnly": true,
    "note": null,
    "sourceSupported": true,
    "autoAttach": true
  },
  {
    "caseName": "In re Search Warrant No. 16-960-M-01 to Google",
    "citation": "232 F.Supp.3d 708",
    "authorityId": "65463744-8938-4d75-8a39-7778a80607ca",
    "courtId": "us-d-pa-ed",
    "jurisdiction": "US",
    "dimension": "PARTICULARITY",
    "doctrine": "FEDERAL_CONSTITUTIONAL",
    "proposition": "search warrants",
    "sourceSpan": "OF DECISION THOMAS J. RUETER, United States Magistrate Judge In August, 2016, this court issued two search warrants, pursuant to section 2703 of the Stored Communications Act, 18 U.S.C. §§ 2701 et seq. (“SCA” or “Act”), which required Google Inc. (“Google”) to disclose to ag",
    "sourceText": "OF DECISION THOMAS J. RUETER, United States Magistrate Judge In August, 2016, this court issued two search warrants, pursuant to section 2703 of the Stored Communications Act, 18 U.S.C. §§ 2701 et seq. (“SCA” or “Act”), which required Google Inc. (“Google”) to disclose to ag",
    "treatment": "UNVERIFIED",
    "treatmentVerification": "unknown",
    "currentnessStatus": "unknown",
    "canonicalSourceUrl": "https://www.courtlistener.com/opinion/7323989/",
    "persuasiveOnly": true,
    "note": null,
    "sourceSupported": true,
    "autoAttach": true
  }
] as const;

export const HOLDING_SCREEN_REJECTED = [
  {
    "caseName": "Fuentes v. Shevin",
    "citation": "407 U.S. 67",
    "authorityId": "ba1412b6-17d0-4f2a-b075-37cc60f69658",
    "title": "Fuentes v. Shevin",
    "reason": "NOT_WARRANT_SUPPRESSION_HOLDING",
    "contentLength": 40000
  },
  {
    "caseName": "United States v. Cronic",
    "citation": "466 U.S. 648",
    "authorityId": "d5a945f9-c188-4f05-8274-db66e486b4ac",
    "title": "United States v. Cronic",
    "reason": "NOT_WARRANT_SUPPRESSION_HOLDING",
    "contentLength": 40000
  },
  {
    "caseName": "Walder v. United States",
    "citation": "347 U.S. 62",
    "authorityId": "a3a5e8bb-5e26-422d-a4d8-b56af4a1d897",
    "reason": "NOT_ATTACHED_TO_WARRANT_DIMENSION",
    "note": "Impeachment use of evidence; not attached as a warrant-issue dimension."
  },
  {
    "caseName": "United States v. Mooty",
    "citation": "96 F.Supp.3d 472",
    "authorityId": "a0a9ad1b-af45-4d21-a46e-409b4ff50d86",
    "reason": "PROPOSITION_NOT_IN_SOURCE"
  },
  {
    "caseName": "Bamont",
    "citation": "163 F.Supp.3d 138",
    "authorityId": "6e544395-7ba1-4f67-95fc-a086db946a4d",
    "title": "Bamont v. Pennsylvania Society for the Prevention of Cruelty to Animals",
    "reason": "HOLDING_REVIEW_REQUIRED_NO_SAFE_SUPPRESSION_PROPOSITION",
    "contentLength": 40000
  },
  {
    "caseName": "Lawson",
    "citation": "124 F.Supp.3d 394",
    "authorityId": "971da801-b9f3-460d-9ad2-afc95dcf4f83",
    "title": "Lawson v. Pennsylvania SPCA",
    "reason": "HOLDING_REVIEW_REQUIRED_NO_SAFE_SUPPRESSION_PROPOSITION",
    "contentLength": 40000
  },
  {
    "caseName": "In re T.B.",
    "citation": "75 A.3d 485",
    "authorityId": "739f13e5-71c9-40b4-a6ee-75d0ea581deb",
    "reason": "PROPOSITION_NOT_IN_SOURCE"
  },
  {
    "caseName": "Pustilnik",
    "citation": "439 A.2d 1149",
    "authorityId": "33068440-94da-422d-bfc8-8ff5bfece006",
    "title": "Associated Hospital Service v. Pustilnik",
    "reason": "NOT_SEARCH_OR_SUPPRESSION_AUTHORITY",
    "contentLength": 13132
  },
  {
    "caseName": "Ness",
    "citation": "105 A.3d 1257",
    "authorityId": "6aac6edc-63d2-44af-aed7-c954f027240d",
    "title": "Ness v. York Township Board of Commissioners",
    "reason": "SOURCE_TOO_THIN_OR_WRONG_CASE",
    "contentLength": 126
  },
  {
    "caseName": "Grigsby",
    "citation": "47 A.3d 1176",
    "authorityId": "7900a059-d314-4004-9eab-12d61a1f64d4",
    "title": "Grigsby v. Department of Corrections Sci-Retreat",
    "reason": "SOURCE_TOO_THIN_OR_WRONG_CASE",
    "contentLength": 89
  }
] as const;

export const HOLDING_SCREEN_IDENTITY = {
  "hostOk": true,
  "cases": 4680,
  "authorities": 6035
} as const;
