/** Turn stored keys into short labels a lawyer can read without guessing. */
const LABELS: Record<string, string> = {
  verified_context: "Confirmed fact",
  strategic_note: "Strategy note",
  entity_resolution: "Who this is",
  document_significance: "Why this file matters",
  factual_caveat: "Caution",
  user_instruction: "Your instruction",
  matter_preference: "Case preference",
  procedural_context: "Procedure",
  other: "Other",
  related_to: "Related to",
  works_for: "Works for",
  party_to: "Party to",
  signed: "Signed",
  sent: "Sent",
  received: "Received",
  attended: "Attended",
  mentioned_in: "Mentioned in",
  supports: "Supports",
  contradicts: "Conflicts with",
  occurred_before: "Occurred before",
  occurred_after: "Occurred after",
  represents: "Represents",
  assigned_to: "Assigned to",
  alleges: "Alleges",
  paid: "Paid",
  owns: "Owns",
  communicates_with: "Communicates with",
  supported_by: "Supported by",
  participated_in: "Participated in",
  contains_fact: "Contains fact",
  party: "Party",
  counsel: "Counsel",
  witness: "Witness",
  matter_entity: "Person or organization",
  timeline_event: "Event",
  matter_fact: "Fact",
  manual_note: "Note",
  communication: "Communication",
  communications: "Communications",
  deadline: "Deadline",
  meeting: "Meeting",
  testimony: "Testimony",
  person: "Person",
  organization: "Organization",
  event: "Event",
  fact: "Fact",
  client: "Client",
  matter: "Case",
  exact: "Exact date",
  approximate: "Approximate date",
  unknown: "Date unknown",
  range: "Date range",
  document: "Document",
  task: "Task",
  deadline_candidate: "Deadline",
  low: "Low",
  normal: "Normal",
  high: "High",
  critical: "Critical",
  uploaded: "Uploaded",
  processing: "Processing",
  ready: "Ready",
  failed: "Failed",
  proposed: "Suggested",
  approved: "Confirmed",
  edited_and_approved: "Edited and confirmed",
  rejected: "Rejected",
  superseded: "Replaced",
  archived: "Archived",
  open: "Open",
  in_progress: "In progress",
  completed: "Done",
  awaiting_approval: "Needs your OK",
  planned: "Queued",
  running: "Working",
  draft: "Draft",
  in_review: "In review",
  individual: "Individual",
  active: "Active",
  posted: "Posted",
  issued: "Issued",
  void: "Void",
  pending: "Pending",
  filed: "Filed",
  discarded: "Discarded",
  released: "Released",
  owner: "Organization owner",
  lawyer: "Lawyer",
  staff: "Staff",
  client_guest: "Client guest",
  suggested: "Suggested",
  manual: "Entered by you",
  verified_deadline: "Verified",
  controlling: "Controlling",
  persuasive: "Persuasive",
  out_of_jurisdiction: "Other jurisdiction",
};

export function humanizeKey(value: string | null | undefined): string {
  if (!value) return "";
  const mapped = LABELS[value];
  if (mapped) return mapped;
  return value.replace(/[_-]+/g, " ");
}
